version: "3.3"

services:
  db:
    command: --max_allowed_packet=268435456
    container_name: Visioneer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure
    image: mariadb # necessary for M1 chips
    ports:
      - 33060:3306
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql:delegated

  memcached:
    container_name: Visioneer_memcached
    image: memcached:1.5

  wordpress:
    container_name: Visioneer_wordpress
    depends_on:
      - db
      - memcached
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: not-so-secure
      DB_NAME: wordpress
      MEMCACHED_HOST: memcached:11211
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
      WP_ENV: development
    image: docker.io/bitpoke/wordpress-runtime:bedrock
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./:/app

volumes:
  db_data: {}
