version: '3.7'

services:
  db:
    container_name: bedrock_db
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    image: mariadb # necessary for M1 chips
    command: --max_allowed_packet=268435456
    ports:
      - 33060:3306
    restart: "no"
    volumes:
      - ./db_data:/var/lib/mysql:delegated

  memcached:
    container_name: bedrock_memcached
    image: memcached:1.5

  nginx-proxy:
    container_name: bedrock_nginx-proxy
    depends_on:
      - wordpress
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./my_nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:delegated
  
  phpmyadmin:
    container_name: bedrock_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    image: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    restart: always

  wordpress:
    container_name: bedrock_wordpress
    depends_on:
      - db
      - memcached
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      MEMCACHED_HOST: memcached:11211
      VIRTUAL_HOST: bedrock.local
    expose:
      - 9003
    image: wordpress_bedrock_xdebug
    restart: "no"
    volumes:
      - ./:/var/www/html:delegated
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

volumes:
  db_data:
